language: minimal
sudo: required
dist: trusty
os:
  - linux
install:
  # Install SBCL
  - sudo apt-get install sbcl

  # Install Quicklisp
  - wget https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --disable-debugger --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql::without-prompting (ql:add-to-init-file))' --eval '(quit)'
  - |
   cat >> ~/.sbclrc <<EOF
   (dolist (dir (directory (merge-pathnames "*/" *default-pathname-defaults*)))
     (pushnew dir asdf:*central-registry* :test #'equal))
  # Hack: This works because it terminates when it fails to see the EOF

script:
  - sbcl --disable-debugger --eval '(ql:quickload :ip-interfaces)' --eval '(format t "~a~%" (ip-interfaces:get-ip-interfaces))' --eval '(quit)'
